### ISSUE TITLE
File paths not working

### ISSUE THREAD

**Issue by dominichayesferen** [lagru/Vivaldi-Thumbs-Replacer#1]
I've tried your program, but after putting in the right paths, it always crashes.
This is the code with the right names:

```
# PATHs - edit only these!
# --------------------------------------------------------------------------- #
topSites_path = 'C:\Users\wwwdp\AppData\Local\Vivaldi\User Data\Default\Top Sites'
bookmark_path = 'C:\Users\wwwdp\AppData\Local\Vivaldi\User Data\Default\Bookmarks'

backup_path = 'C:\Users\wwwdp\Desktop\'
customThumbs_path = 'C:\Users\wwwdp\AppData\Local\Vivaldi\Application\1.3.537.5\resources\vivaldi\resources'
# --------------------------------------------------------------------------- #
```

What am I doing wrong for it to keep crashing?

**Comment by dominichayesferen** [comment]
UPDATE: Changed the paths, but it's still crashing:

```
topSites_path = 'C:\Users\wwwdp/AppData/Local/Vivaldi/User Data/Default/Top Sites'
bookmark_path = 'C:\Users/wwwdp/AppData/Local/Vivaldi/User Data/Default/Bookmarks'

backup_path = 'C:/Users/wwwdp/Desktop/'
customThumbs_path = 'C:/Users/wwwdp/Pictures/Custom Thumbnails/'
```

**Comment by dominichayesferen** [comment]
Nope, wait, fixed it thanks!

```
topSites_path = 'C:/Users/wwwdp/AppData/Local/Vivaldi/User Data/Default/Top Sites'
bookmark_path = 'C:/Users/wwwdp/AppData/Local/Vivaldi/User Data/Default/Bookmarks'

backup_path = 'C:/Users/wwwdp/Desktop/'
customThumbs_path = 'C:/Users/wwwdp/Pictures/Custom Thumbnails/'
```

**Comment by lagru** [comment]
Glad you figured it out by yourself. One thing to keep in mind is how python and os.path use strings. So Copy&Pasting Windows paths doesn't work. You need to replace "\" with "/". You can read more on the issue [here](https://pythonconquerstheuniverse.wordpress.com/2008/06/04/gotcha-—-backslashes-in-windows-filenames/).

I will clarify this in the README.

**Comment by dominichayesferen** [comment]
@lagru , just tried it in Linux, and I'm now getting this error:

```
Traceback (most recent call last):
  File "/home/vivaldiconfigurations/Downloads/Vivaldi-Thumbs-Replacer-master/vivaldiThumbsReplacer.py", line 110, in <module>
    main()
  File "/home/vivaldiconfigurations/Downloads/Vivaldi-Thumbs-Replacer-master/vivaldiThumbsReplacer.py", line 79, in main
    input("\nWARNING: Please make sure that Vivaldi isn't running. Press 'Enter' to continue.")
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing
```

Any advice?

BTW, here's my paths:

```
# PATHs - edit only these!
# --------------------------------------------------------------------------- #
topSites_path = '/home/vivaldiconfigurations/.config/vivaldi/Default/Top Sites'
bookmark_path = '/home/vivaldiconfigurations/.config/vivaldi/Default/Bookmarks'

backup_path = '/home/vivaldiconfigurations/Desktop/Backups'
customThumbs_path = '/home/vivaldiconfigurations/Desktop/Custom Thumbnails'
# --------------------------------------------------------------------------- #
```

**Comment by lagru** [comment]
I opened a seperate issue #3  for this.
